export const PersianTexts = {
  groups: 'گروه‌ها',
  channels: 'کانال‌ها',
  whatsapp: 'واتساپ',
  home: 'خانه',
  searchGroups: 'جستجوی گروه‌ها...',
  searchChannels: 'جستجوی کانال‌ها...',
  searchAll: 'جستجو در همه...',
  noGroupsFound: 'گروهی یافت نشد',
  noChannelsFound: 'کانالی یافت نشد',
  noItemsFound: 'موردی یافت نشد',
  members: 'عضو',
  premium: 'ویژه',
  manager: 'مدیر',
  category: 'دسته‌بندی',
  link: 'لینک',
  description: 'توضیحات',
  openLink: 'باز کردن لینک',
  sendLink: 'ارسال لینک',
  success: 'موفقیت',
  error: 'خطا',
  linkSentSuccessfully: 'لینک با موفقیت ارسال شد!',
  failedToSendLink: 'ارسال لینک ناموفق بود. دوباره تلاش کنید.',
  unexpectedError: 'خطای غیرمنتظره رخ داد.',
  cannotOpenLink: 'امکان باز کردن این لینک وجود ندارد',
  failedToOpenLink: 'باز کردن لینک ناموفق بود',
  itemNotFound: 'آیتم یافت نشد',
  retry: 'تلاش مجدد',
  watchAdToSend: 'برای ارسال لینک، ابتدا تبلیغ را مشاهده کنید',
  adNotReady: 'تبلیغ آماده نیست. لطفاً کمی صبر کنید.',
  adWatchedSuccessfully: 'تبلیغ با موفقیت مشاهده شد!',
  loadingAd: 'در حال بارگذاری تبلیغ...',
  filter: 'فیلتر',
  
  // Welcome messages
  welcomeTitle: 'به واتساپ لینک دونی خوش آمدید',
  welcomeSubtitle: 'بهترین کانال‌ها و گروه‌های واتساپ را کشف کنید',
  
  // Add Link Form
  addNewLink: 'افزودن لینک جدید',
  name: 'نام',
  type: 'نوع',
  channel: 'کانال',
  group: 'گروه',
  ad: 'تبلیغ',
  imageUrl: 'آدرس تصویر',
  addLink: 'افزودن لینک',
  submitting: 'در حال ارسال...',
  
  // Placeholders
  enterName: 'نام کانال/گروه را وارد کنید',
  enterLink: 'لینک واتساپ را وارد کنید',
  enterManager: 'نام مدیر را وارد کنید',
  enterCategory: 'دسته‌بندی را وارد کنید',
  enterDescription: 'توضیحات را وارد کنید',
  enterMembers: 'تعداد اعضا را وارد کنید',
  enterImageUrl: 'آدرس تصویر را وارد کنید (اختیاری)',
  
  // Validation
  nameRequired: 'نام الزامی است',
  linkRequired: 'لینک الزامی است',
  managerRequired: 'نام مدیر الزامی است',
  categoryRequired: 'دسته‌بندی الزامی است',
  descriptionRequired: 'توضیحات الزامی است',
  membersRequired: 'تعداد اعضا باید عدد باشد',
  
  // Success messages
  linkAddedSuccessfully: 'لینک با موفقیت اضافه شد و در انتظار تایید است',
  failedToAddLink: 'افزودن لینک ناموفق بود. دوباره تلاش کنید.',
  ok: 'باشه',
};
